# Generated by Django 6.0.3 on 2026-04-08 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
